name: auto-sync
run-name: Auto Sync
on:
  # Runs every day at 4:00am
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  read-tournament-ids:
    name: Read Tournament Id List
    runs-on: ubuntu-20.04
    outputs:
      TOURNAMENT_IDS: ${{ steps.step1.outputs.TOURNAMENT_IDS }}
    steps:
      - uses: actions/checkout@v3
      - id: step1
        name: Output id list
        run: echo "TOURNAMENT_IDS=$(cat auto.txt | tr '\n' ' ')" >> "$GITHUB_OUTPUT"
  sync-auto:
    name: Sync
    uses: ./.github/workflows/sync.yml
    needs: read-tournament-ids
    with:
      TOURNAMENT_IDS: ${{ needs.read-tournament-ids.outputs.TOURNAMENT_IDS }}
    secrets:
      START_GG_API_KEY: ${{ secrets.START_GG_API_KEY }}
      KCFGC_DEPLOY_KEY: ${{ secrets.KCFGC_DEPLOY_KEY }}
