name: sync
run-name: Sync
on:
  workflow_call:
    inputs:
      TOURNAMENT_IDS:
        required: true
        type: string
    secrets:
      START_GG_API_KEY:
        required: true

jobs:
  extract:
    name: Extract Tournament Info
    runs-on: ubuntu-20.04
    env:
      START_GG_API_KEY: ${{ secrets.START_GG_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: npm run build
      - name: Extract
        run: node packages/start-gg/dist/index.js ${{ inputs.TOURNAMENT_IDS }} > output/start-gg-tournaments.json
      - name: Upload start.gg output
        uses: actions/upload-artifact@v3
        with:
          name: start-gg-tournaments.json
          path: output/start-gg-tournaments.json

  generate-website:
    name: Generate Website Files
    runs-on: ubuntu-20.04
    needs: extract
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: npm run build
      - name: Download start.gg output
        uses: actions/download-artifact@v3
        with:
          name: start-gg-tournaments.json
      - name: Generate website files
        run: node packages/website/dist/index.js --out-dir=./output < start-gg-tournaments.json
      - name: Upload website files output
        uses: actions/upload-artifact@v3
        with:
          name: website-files
          path: output/*.md

  upload-website:
    name: Upload Website Files
    runs-on: ubuntu-20.04
    needs: generate-website
    steps:
      - uses: actions/checkout@v3
        with:
          repository: kcfgc/kcfgc.github.io
      - name: Download website files output
        uses: actions/download-artifact@v3
        with:
          name: website-files
          path: content/events
      - run: git diff
      - run: ls -al content
      - run: ls -al content/events
